module.exports = {
  extends: ["@commitlint/config-conventional"],
  rules: {
    "type-enum": [
      2,
      "always",
      [
        "feat",
        "fix",
        "docs",
        "style",
        "refactor",
        "perf",
        "test",
        "chore",
        "ci",
        "build",
        "revert",
      ],
    ],
    "type-case": [2, "always", "lower-case"],
    "type-empty": [2, "never"],
    "subject-empty": [2, "never"],
    "subject-full-stop": [2, "never", "."],
    "subject-case": [
      2,
      "always",
      ["lower-case"],
      // Allow subject to start with any letter; we use imperative mood lower-case
    ],
    "header-max-length": [2, "always", 100],
    "body-leading-blank": [2, "always"],
    "body-max-line-length": [2, "always", 100],
    "footer-leading-blank": [2, "always"],
    "footer-max-line-length": [2, "always", 100],
    "scope-enum": [
      2,
      "always",
      [
        "data",
        "metrics",
        "plotting",
        "analysis",
        "agata",
        "utils",
        "docs",
        "ci",
        "deps",
        "release",
        "agents",
        "examples",
        "tests",
        "harness",
        "tooling",
      ],
    ],
    "scope-empty": [1, "never"],
  },
  prompt: {
    questions: [
      {
        type: "list",
        name: "type",
        message: "What is the type of this commit?",
        choices: [
          "feat",
          "fix",
          "docs",
          "style",
          "refactor",
          "perf",
          "test",
          "chore",
          "ci",
          "build",
          "revert",
        ],
      },
      {
        type: "list",
        name: "scope",
        message: "What is the scope of this commit? (optional)",
        choices: [
          "data",
          "metrics",
          "plotting",
          "analysis",
          "agata",
          "utils",
          "docs",
          "ci",
          "deps",
          "release",
          "agents",
          "examples",
          "tests",
          "harness",
          "tooling",
        ],
      },
      {
        type: "input",
        name: "subject",
        message: "Write a short, imperative description (< 100 chars):",
      },
      {
        type: "input",
        name: "body",
        message: "Provide a longer description (optional, press enter to skip):",
      },
      {
        type: "input",
        name: "breaking",
        message: "Describe the breaking change (optional, press enter to skip):",
      },
    ],
  },
};
