"""Deterministic generator for the v0.5.2 synthetic test fixtures.

This script writes hand-validated, byte-for-byte reproducible CSV fixtures
under tests/fixtures/. It is intentionally NOT a test itself; it is a
maintenance script that documents the construction of the fixtures.

Re-run only when the device format (column names, timestamp format)
changes in cgmpy/data/specialized.py.

Usage:
    python scripts/generate_fixtures_v052.py
"""

from __future__ import annotations

import math
from pathlib import Path

import pandas as pd


# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
N_ROWS_24H = 288  # 24h at 5-min intervals
N_ROWS_1H = 12  # 1h at 5-min intervals
START = pd.Timestamp("2024-01-01 00:00:00")
GLUCOSE_CONSTANT = 120  # mg/dL

# Device-specific column names (must match cgmpy/data/specialized.py)
DEXCOM_DATE = "Marca temporal (AAAA-MM-DDThh:mm:ss)"
DEXCOM_GLUCOSE = "Nivel de glucosa (mg/dL)"

LIBREVIEW_DATE = "Sello de tiempo del dispositivo"
LIBREVIEW_GLUCOSE = "Historial de glucosa mg/dL"

MEDTRONIC_DATE = "Fecha y hora"
MEDTRONIC_GLUCOSE = "Valor del sensor (mg/dL)"

TANDEM_DATE = "Timestamp"
TANDEM_GLUCOSE = "CGM Glucose Value (mg/dL)"


def _out(base: Path, *parts: str) -> Path:
    return base.joinpath(*parts)


# ---------------------------------------------------------------------------
# Device fixtures (constant 120 mg/dL, 24h at 5-min intervals, 288 rows)
# ---------------------------------------------------------------------------
def _build_timestamps_24h() -> list[pd.Timestamp]:
    """Return 288 evenly spaced 5-min timestamps starting at 2024-01-01 00:00:00."""
    return list(pd.date_range(start=START, periods=N_ROWS_24H, freq="5min"))


def write_dexcom_constant_120(base: Path) -> Path:
    path = _out(base, "devices", "dexcom_constant_120.csv")
    timestamps = _build_timestamps_24h()
    df = pd.DataFrame(
        {
            DEXCOM_DATE: [t.strftime("%Y-%m-%dT%H:%M:%S") for t in timestamps],
            DEXCOM_GLUCOSE: [GLUCOSE_CONSTANT] * N_ROWS_24H,
        }
    )
    df.to_csv(path, index=False, lineterminator="\n")
    return path


def write_libreview_constant_120(base: Path) -> Path:
    """Libreview has 2 banner rows above the actual header (header=2)."""
    path = _out(base, "devices", "libreview_constant_120.csv")
    timestamps = _build_timestamps_24h()
    with path.open("w", encoding="utf-8", newline="") as fh:
        # Two banner rows (skipped by header=2)
        fh.write("Patient export\n")
        fh.write("Generated by Libreview\n")
        # Real header on row index 2 (0-based)
        fh.write(
            f"Dispositivo,Numero de serie,{LIBREVIEW_DATE},Tipo de registro,{LIBREVIEW_GLUCOSE}\n"
        )
        for t in timestamps:
            # Libreview uses DD-MM-YYYY HH:MM (no seconds)
            fh.write(f"FreeStyle Libre 3,XXX,{t.strftime('%d-%m-%Y %H:%M')},0,{GLUCOSE_CONSTANT}\n")
    return path


def write_medtronic_constant_120(base: Path) -> Path:
    path = _out(base, "devices", "medtronic_constant_120.csv")
    timestamps = _build_timestamps_24h()
    df = pd.DataFrame(
        {
            MEDTRONIC_DATE: [t.strftime("%Y-%m-%d %H:%M:%S") for t in timestamps],
            MEDTRONIC_GLUCOSE: [GLUCOSE_CONSTANT] * N_ROWS_24H,
        }
    )
    df.to_csv(path, index=False, lineterminator="\n")
    return path


def write_tandem_constant_120(base: Path) -> Path:
    path = _out(base, "devices", "tandem_constant_120.csv")
    timestamps = _build_timestamps_24h()
    df = pd.DataFrame(
        {
            TANDEM_DATE: [t.strftime("%Y-%m-%d %H:%M:%S") for t in timestamps],
            TANDEM_GLUCOSE: [GLUCOSE_CONSTANT] * N_ROWS_24H,
        }
    )
    df.to_csv(path, index=False, lineterminator="\n")
    return path


# ---------------------------------------------------------------------------
# Edge cases (Dexcom format, 1h at 5-min intervals unless noted)
# ---------------------------------------------------------------------------
def write_edge_empty(base: Path) -> Path:
    """Header only, no data rows."""
    path = _out(base, "devices", "edge_cases", "empty.csv")
    with path.open("w", encoding="utf-8", newline="") as fh:
        fh.write(f"{DEXCOM_DATE},{DEXCOM_GLUCOSE}\n")
    return path


def write_edge_single_row(base: Path) -> Path:
    """Exactly 1 data row, value 100 mg/dL."""
    path = _out(base, "devices", "edge_cases", "single_row.csv")
    df = pd.DataFrame(
        {
            DEXCOM_DATE: [START.strftime("%Y-%m-%dT%H:%M:%S")],
            DEXCOM_GLUCOSE: [100],
        }
    )
    df.to_csv(path, index=False, lineterminator="\n")
    return path


def write_edge_all_nan(base: Path) -> Path:
    """12 rows, glucose column is entirely NaN."""
    path = _out(base, "devices", "edge_cases", "all_nan_glucose.csv")
    timestamps = list(pd.date_range(start=START, periods=N_ROWS_1H, freq="5min"))
    df = pd.DataFrame(
        {
            DEXCOM_DATE: [t.strftime("%Y-%m-%dT%H:%M:%S") for t in timestamps],
            DEXCOM_GLUCOSE: [float("nan")] * N_ROWS_1H,
        }
    )
    df.to_csv(path, index=False, lineterminator="\n")
    return path


def write_edge_with_gap(base: Path) -> Path:
    """12 rows with a 30-min gap in the middle (Dexcom format).

    Layout: minutes 0-25 (6 rows), then minutes 55-80 (6 rows). The gap is
    the 30-minute window 25-55 with no readings.
    """
    path = _out(base, "devices", "edge_cases", "with_gap.csv")
    times_part1 = [START + pd.Timedelta(minutes=5 * i) for i in range(0, 6)]  # 0..25
    times_part2 = [START + pd.Timedelta(minutes=5 * i) for i in range(11, 17)]  # 55..80
    timestamps = times_part1 + times_part2
    df = pd.DataFrame(
        {
            DEXCOM_DATE: [t.strftime("%Y-%m-%dT%H:%M:%S") for t in timestamps],
            DEXCOM_GLUCOSE: [GLUCOSE_CONSTANT] * len(timestamps),
        }
    )
    df.to_csv(path, index=False, lineterminator="\n")
    return path


def write_edge_out_of_range_high(base: Path) -> Path:
    """12 rows, one value of 700 mg/dL (above the 600 mg/dL ceiling)."""
    path = _out(base, "devices", "edge_cases", "out_of_range_high.csv")
    timestamps = list(pd.date_range(start=START, periods=N_ROWS_1H, freq="5min"))
    values = [GLUCOSE_CONSTANT] * N_ROWS_1H
    values[6] = 700  # mid-row anomaly
    df = pd.DataFrame(
        {
            DEXCOM_DATE: [t.strftime("%Y-%m-%dT%H:%M:%S") for t in timestamps],
            DEXCOM_GLUCOSE: values,
        }
    )
    df.to_csv(path, index=False, lineterminator="\n")
    return path


def write_edge_out_of_range_low(base: Path) -> Path:
    """12 rows, one value of 20 mg/dL (below the 39 mg/dL floor)."""
    path = _out(base, "devices", "edge_cases", "out_of_range_low.csv")
    timestamps = list(pd.date_range(start=START, periods=N_ROWS_1H, freq="5min"))
    values = [GLUCOSE_CONSTANT] * N_ROWS_1H
    values[6] = 20  # mid-row anomaly
    df = pd.DataFrame(
        {
            DEXCOM_DATE: [t.strftime("%Y-%m-%dT%H:%M:%S") for t in timestamps],
            DEXCOM_GLUCOSE: values,
        }
    )
    df.to_csv(path, index=False, lineterminator="\n")
    return path


# ---------------------------------------------------------------------------
# Synthetic (non-device-bound) fixtures
# ---------------------------------------------------------------------------
def write_sine_24h(base: Path) -> Path:
    """g(t) = 120 + 30 * sin(2*pi*t/720), t in minutes, 5-min samples, 24h.

    The chosen 24h window (288 samples) contains exactly 2 full periods
    (288 / (720/5) = 288/144 = 2), so:
      - mean(g) = 120 exactly
      - sample SD (ddof=1) = 30 * sqrt((287/288) * 1/2) = 30*sqrt(287/576)
        = 30 * sqrt(0.4982638888...) = 30 * 0.705878... = 21.1766...
      - min = 90, max = 150
      - TIR 70-180 = 100% (everything inside [90, 150])
      - GMI = round(3.31 + 0.02392*120, 2) = 6.18
    """
    path = _out(base, "synthetic", "sine_24h.csv")
    timestamps = list(pd.date_range(start=START, periods=N_ROWS_24H, freq="5min"))
    minutes = [int((t - START).total_seconds() // 60) for t in timestamps]
    glucose = [120 + 30 * math.sin(2 * math.pi * m / 720) for m in minutes]
    df = pd.DataFrame({"time": timestamps, "glucose": glucose})
    df.to_csv(path, index=False, lineterminator="\n")
    return path


# ---------------------------------------------------------------------------
# Driver
# ---------------------------------------------------------------------------
def main() -> None:
    base = Path("tests/fixtures")
    writers = [
        # Device fixtures
        ("dexcom_constant_120.csv", write_dexcom_constant_120),
        ("libreview_constant_120.csv", write_libreview_constant_120),
        ("medtronic_constant_120.csv", write_medtronic_constant_120),
        ("tandem_constant_120.csv", write_tandem_constant_120),
        # Edge cases
        ("edge_cases/empty.csv", write_edge_empty),
        ("edge_cases/single_row.csv", write_edge_single_row),
        ("edge_cases/all_nan_glucose.csv", write_edge_all_nan),
        ("edge_cases/with_gap.csv", write_edge_with_gap),
        ("edge_cases/out_of_range_high.csv", write_edge_out_of_range_high),
        ("edge_cases/out_of_range_low.csv", write_edge_out_of_range_low),
        # Synthetic
        ("sine_24h.csv", write_sine_24h),
    ]
    for _rel, fn in writers:
        out = fn(base)
        size = out.stat().st_size
        print(f"  {out}  ({size} bytes)")


if __name__ == "__main__":
    main()
