"""Base mixin and shared utilities for variability metrics."""

from __future__ import annotations

import logging
from typing import TYPE_CHECKING, Any

import numpy as np
import pandas as pd

if TYPE_CHECKING:
    pass

logger = logging.getLogger(__name__)


class VariabilityBase:
    """Base mixin that provides type stubs for cross-mixin dependencies.

    Subclasses of this class (e.g. :class:`SDMetrics`,
    :class:`MAGEMetrics`) are designed to be combined with
    :class:`~cgmpy.data.core.ModularGlucoseData` to form a fully
    functional variability-metrics facade.
    """

    if TYPE_CHECKING:
        data: pd.DataFrame
        typical_interval: float
        log: bool
        logger: logging.Logger

        def sd(self) -> float: ...
        def mean(self) -> float: ...
        def median(self) -> float: ...
        def cv(self) -> float: ...
        def gmi(self) -> float: ...
        def data_completeness(self) -> float: ...
        def TBR(self, threshold: float) -> float: ...
        def TAR(self, threshold: float) -> float: ...
        def calculate_time_in_range(self, low: float, high: float) -> float: ...
        def TIR(self) -> float: ...
        def TIR_tight(self) -> float: ...
        def TIR_pregnancy(self) -> float: ...
        def TAR180(self) -> float: ...
        def TAR250(self) -> float: ...
        def TAR140(self) -> float: ...
        def TBR70(self) -> float: ...
        def TBR63(self) -> float: ...
        def TBR55(self) -> float: ...
        def current_targets(self) -> Any: ...
